# paths
repo_root: "."
data_path: data/csi_datasets/
yt_metadata_file: data/yt_metadata.parquet
device: cuda

#
learning_rate: 0.0001 # 1e-4

# losses
arcface_loss:
  num_classes: 5324
  embedding_size: 384
  scale: 4 # default: 64
  margin: 28.6
contrastive_loss:
  pos_margin: 0
  neg_margin: 1
multisimilarity_loss:
  alpha: 2
  beta: 50
  base: 0.5
ntxent_loss:
  temperature: 0.7
triplet_loss:
  margin: 0.3 # default 0.05



